# Generated by Django 3.1.6 on 2021-03-05 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0002_blogmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sampleModel',
        ),
    ]
